### ISSUE TITLE
TypeError: Expected string or buffer

### ISSUE THREAD

**Issue by dorneanu** [lqez/pelican-embed-tweet#2]
Hi!

Your plugin has a bug: 

```
CRITICAL: TypeError: expected string or buffer
Traceback (most recent call last):
  File "/home/victor/work/blog/pelican/env/bin/pelican", line 11, in <module>
    sys.exit(main())
  File "/home/victor/work/blog/pelican/env/lib/python2.7/site-packages/pelican/__init__.py", line 456, in main
    pelican.run()
  File "/home/victor/work/blog/pelican/env/lib/python2.7/site-packages/pelican/__init__.py", line 175, in run
    p.generate_context()
  File "/home/victor/work/blog/pelican/env/lib/python2.7/site-packages/pelican/generators.py", line 702, in generate_context
    context_sender=self)
  File "/home/victor/work/blog/pelican/env/lib/python2.7/site-packages/pelican/readers.py", line 548, in read_file
    context=context)
  File "/home/victor/work/blog/pelican/env/lib/python2.7/site-packages/pelican/contents.py", line 370, in __init__
    super(Static, self).__init__(*args, **kwargs)
  File "/home/victor/work/blog/pelican/env/lib/python2.7/site-packages/pelican/contents.py", line 149, in __init__
    signals.content_object_init.send(self)
  File "/home/victor/work/blog/pelican/env/lib/python2.7/site-packages/blinker/base.py", line 267, in send
    for receiver in self.receivers_for(sender)]
  File "/home/victor/work/blog/pelican/extra-plugins/pelican-embed-tweet/embed_tweet.py", line 34, in embed_tweet
    content._content
  File "/home/victor/work/blog/pelican/env/lib/python2.7/re.py", line 155, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or buffer

```

**Comment by lqez** [comment]
Agrrrrr. I actually experienced this error before. But I didn't updated the repo.
I pushed it - https://github.com/lqez/pelican-embed-tweet/commit/8d85bfd34c291f01235eb630f458972cc11c58ad
